version: '3.7'

services:
  auth:
    build: auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DNS: postgresql://postgres:password@db:5432/auth?sslmode=disable
    command:
      - "-port"
      - "50051"
      - "-bearer-duration"
      - "8h"

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 60
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build: api
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=50051
    volumes:
      - ./api/src:/app
    ports:
      - "80:80"

volumes:
  postgres:
